# cliff.toml
[changelog]
# æ—¥å¿—çš„æ ¼å¼æ¨¡æ¿
body = """
## What's Changed
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in commits %}
- {{ commit.message }} ({{ commit.id | truncate(length=7, end="") }})
{% endfor %}
{% endfor %}
"""
# å»é™¤å¤šä½™çš„æ¢è¡Œ
trim = true

[git]
# è§£æ commit è®°å½•
conventional_commits = true
filter_unconventional = false
split_commits = false
# é’ˆå¯¹ä¸ªäººé¡¹ç›®çš„åˆ†ç±»é€»è¾‘
commit_parsers = [
  { message = "^feat", group = "<!-- 0 -->ğŸš€ Features" },
  { message = "^fix", group = "<!-- 1 -->ğŸ› Bug Fixes" },
  { message = "^doc", group = "<!-- 3 -->ğŸ“š Documentation" },
  { message = "^perf", group = "<!-- 4 -->âš¡ Performance" },
  { message = "^refactor", group = "<!-- 2 -->ğŸšœ Refactor" },
  { message = "^style", group = "<!-- 5 -->ğŸ¨ Styling" },
  { message = "^test", group = "<!-- 6 -->ğŸ§ª Testing" },
  { message = "^chore\\(release\\): prepare for", skip = true },
  { message = "^chore\\(deps.*\\)", skip = true },
  { message = "^chore\\(pr\\)", skip = true },
  { message = "^chore\\(pull\\)", skip = true },
  { message = ".*", group = "<!-- 7 -->âš™ï¸ Miscellaneous" }, # å…¶ä»–æ²¡å†™å‰ç¼€çš„éƒ½å½’åˆ°è¿™é‡Œ
]
protect_breaking_commits = false
filter_commits = false
tag_pattern = "v[0-9].*"
skip_tags = "beta|alpha"
ignore_tags = ""
sort_commits = "oldest"
